# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install libmagick++-dev libudunits2-dev libgdal-dev build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev

